export const phrasesList = {
  Państwa: [
    'Bośnia i Hercegowina',
    'Finlandia',
    'Macedonia',
    'Wyspy Zielonego Przylądka',
    'Mauretania',
    'Sierra Leone',
    'Kamerun',
    'Zjednoczone Emiraty Arabskie',
    'Turkmenistan',
    'Singapur',
    'Kolumbia',
    'Filipiny',
    'Stany Zjednoczone',
    'Australia',
    'Honduras',
  ],
  Filmy: [
    'Ojciec Chrzestny',
    'Narodziny Gwiazdy',
    'Mission Impossible',
    'Gwiezdne Wojny',
    'Gdzie Jest Nemo',
    'Zielona Mila',
    'Forrest Gump',
    'Skazani Na Shawshank',
    'Pulp Fiction',
    'Władca Pierścieni',
    'Matrix',
    'Milczenie owiec',
    'Podziemny krąg',
    'Epoka lodowcowa',
    'Szeregowiec Ryan',
  ],
  Przysłowia: [
    'Bez Pracy Nie Ma Kołaczy',
    'Fortuna Kołem Się Toczy',
    'Nie Chwal Dnia Przed Zachodem Słońca',
    'Apetyt Rośnie W Miarę Jedzenia',
    'Co Ma Wisieć Nie Utonie',
    'Dzieci I Ryby Głosu Nie Mają',
    'Grosz Do Grosza A Będzie Kokosza',
    'Pieniądze Szczęścia Nie Dają',
    'Winny Się Tłumaczy',
    'Szczęśliwi Czasu Nie Liczą',
    'Niedaleko Pada Jabłko Od Jabłoni',
    'Pierwsze Koty Za Płoty',
    'Znać Się Jak Łyse Konie',
    'Trafiło Się Ślepej Kurze Ziarno',
    'Baba Z Wozu Koniom Lżej',
  ],
  Ludzie: [
    'Steve Jobs',
    'Barack Obama',
    'Robert Lewandowski',
    'Marilyn Monroe',
    'Abraham Lincoln',
    'Nelson Mandela',
    'Królowa Elżbieta',
    'Bill Gates',
    'Elon Musk',
    'Elvis Presley',
    'Leonardo Da Vinci',
    'Dalai Lama',
    'John Lennon',
    'Michael Jackson',
    'Michael Jordan',
  ],
  Przeboje: [
    'Ciągle Pada',
    'Szczęśliwej Drogi Już Czas',
    'Nie Płacz Ewka',
    'Piosenka Księżycowa',
    'Myśli I Słowa',
    'Zostawcie Titanica',
    'Kwiaty We Włosach',
    'Śpij Kochanie Śpij',
    'Dziwny Jest Ten Świat',
    'Dni Których Nie Znamy',
    'Prawy Do Lewego',
    'Chłopaki Nie Płaczą',
    'Dumka Na Dwa Serca',
    'Nie Liczę Godzin I Lat',
    'Windą Do Nieba',
  ],
};
